-- Railway Parcel Management System
-- Oracle 21c / Oracle XE

BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PARCEL_STATUS_TRACKING'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE BOOK_PARCEL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION CALCULATE_PARCEL_CHARGE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PARCEL_TRACKING CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PARCELS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TRAINS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE CUSTOMERS (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20) UNIQUE NOT NULL,
    email VARCHAR2(120),
    address VARCHAR2(250),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TRAINS (
    train_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    train_number VARCHAR2(20) UNIQUE NOT NULL,
    train_name VARCHAR2(100) NOT NULL,
    source VARCHAR2(80) NOT NULL,
    destination VARCHAR2(80) NOT NULL,
    departure_time TIMESTAMP,
    arrival_time TIMESTAMP
);

CREATE TABLE PARCELS (
    parcel_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    train_id NUMBER NOT NULL,
    parcel_type VARCHAR2(50) NOT NULL,
    description VARCHAR2(250),
    weight NUMBER(10,2) NOT NULL CHECK (weight > 0),
    distance_km NUMBER(10,2) NOT NULL CHECK (distance_km > 0),
    charge NUMBER(12,2) NOT NULL,
    status VARCHAR2(30) DEFAULT 'BOOKED' NOT NULL,
    booking_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_parcel_customer FOREIGN KEY (customer_id) REFERENCES CUSTOMERS(customer_id),
    CONSTRAINT fk_parcel_train FOREIGN KEY (train_id) REFERENCES TRAINS(train_id),
    CONSTRAINT chk_parcel_status CHECK (status IN ('BOOKED','IN_TRANSIT','DELIVERED','CANCELLED'))
);

CREATE TABLE PARCEL_TRACKING (
    tracking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parcel_id NUMBER NOT NULL,
    old_status VARCHAR2(30),
    new_status VARCHAR2(30) NOT NULL,
    tracking_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remarks VARCHAR2(250),
    CONSTRAINT fk_tracking_parcel FOREIGN KEY (parcel_id) REFERENCES PARCELS(parcel_id)
);

CREATE INDEX idx_parcels_customer ON PARCELS(customer_id);
CREATE INDEX idx_parcels_train ON PARCELS(train_id);
CREATE INDEX idx_tracking_parcel ON PARCEL_TRACKING(parcel_id);

-- Function: parcel charge based on weight + distance.
CREATE OR REPLACE FUNCTION CALCULATE_PARCEL_CHARGE(
    p_weight NUMBER,
    p_distance NUMBER
) RETURN NUMBER
IS
    v_charge NUMBER(12,2);
BEGIN
    -- Base ₹50 + ₹20/kg + ₹0.50/km
    v_charge := 50 + (p_weight * 20) + (p_distance * 0.50);
    RETURN ROUND(v_charge, 2);
END;
/

-- Procedure: book parcel.
CREATE OR REPLACE PROCEDURE BOOK_PARCEL(
    p_customer_id IN NUMBER,
    p_train_id IN NUMBER,
    p_parcel_type IN VARCHAR2,
    p_description IN VARCHAR2,
    p_weight IN NUMBER,
    p_distance IN NUMBER,
    p_parcel_id OUT NUMBER
)
IS
    v_charge NUMBER(12,2);
BEGIN
    IF p_weight <= 0 OR p_distance <= 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Weight and distance must be greater than zero');
    END IF;

    v_charge := CALCULATE_PARCEL_CHARGE(p_weight, p_distance);

    INSERT INTO PARCELS(
        customer_id, train_id, parcel_type, description,
        weight, distance_km, charge, status
    ) VALUES (
        p_customer_id, p_train_id, p_parcel_type, p_description,
        p_weight, p_distance, v_charge, 'BOOKED'
    ) RETURNING parcel_id INTO p_parcel_id;

    INSERT INTO PARCEL_TRACKING(parcel_id, old_status, new_status, remarks)
    VALUES (p_parcel_id, NULL, 'BOOKED', 'Parcel booked');

    COMMIT;
END;
/

-- Trigger: every status change creates a tracking row.
CREATE OR REPLACE TRIGGER TRG_PARCEL_STATUS_TRACKING
AFTER UPDATE OF status ON PARCELS
FOR EACH ROW
WHEN (OLD.status <> NEW.status)
BEGIN
    INSERT INTO PARCEL_TRACKING(parcel_id, old_status, new_status, remarks)
    VALUES (:NEW.parcel_id, :OLD.status, :NEW.status, 'Status updated');
END;
/

-- JOIN requirement
SELECT p.parcel_id, c.name AS customer_name, c.phone,
       t.train_number, t.train_name, t.source, t.destination,
       p.weight, p.charge, p.status
FROM PARCELS p
JOIN CUSTOMERS c ON p.customer_id = c.customer_id
JOIN TRAINS t ON p.train_id = t.train_id
ORDER BY p.parcel_id;

-- Subquery requirement: trains carrying more parcels than the average number of parcels per train.
SELECT t.train_id, t.train_number, t.train_name, COUNT(p.parcel_id) AS parcel_count
FROM TRAINS t
LEFT JOIN PARCELS p ON p.train_id = t.train_id
GROUP BY t.train_id, t.train_number, t.train_name
HAVING COUNT(p.parcel_id) > (
    SELECT AVG(parcel_count)
    FROM (
        SELECT COUNT(p2.parcel_id) AS parcel_count
        FROM TRAINS t2
        LEFT JOIN PARCELS p2 ON p2.train_id = t2.train_id
        GROUP BY t2.train_id
    )
);

-- Sample data
INSERT INTO CUSTOMERS(name, phone, email, address) VALUES ('Arun Kumar','9876543210','arun@example.com','Chennai');
INSERT INTO CUSTOMERS(name, phone, email, address) VALUES ('Priya S','9876543211','priya@example.com','Coimbatore');
INSERT INTO CUSTOMERS(name, phone, email, address) VALUES ('Rahul M','9876543212','rahul@example.com','Madurai');

INSERT INTO TRAINS(train_number, train_name, source, destination, departure_time, arrival_time)
VALUES ('12601','Chennai Express','Chennai','Mumbai',SYSTIMESTAMP,SYSTIMESTAMP+1);
INSERT INTO TRAINS(train_number, train_name, source, destination, departure_time, arrival_time)
VALUES ('12602','Coimbatore Express','Chennai','Coimbatore',SYSTIMESTAMP,SYSTIMESTAMP+0.3);
INSERT INTO TRAINS(train_number, train_name, source, destination, departure_time, arrival_time)
VALUES ('12603','Pandian Express','Chennai','Madurai',SYSTIMESTAMP,SYSTIMESTAMP+0.5);

COMMIT;
